### ISSUE TITLE
Exception when sending file

### ISSUE THREAD

**Issue by ggajos** [Nerodesk/nerodesk#137]
When i put name of file 1111, attach file and click `Send`
I'm getting:

```
java.lang.IllegalArgumentException: header line of HTTP response "Set-Cookie: RsFlash=file "1111" uploaded;Path=/;Expires=Ĺr, 25 mar 2015 18:45:01 GMT" doesn't match "[a-zA-Z\-]+:\p{Print}+" regular expression, but it should, according to RFC 7230
    at org.takes.rs.RsPrint.print(RsPrint.java:114)
    at org.takes.http.BkBasic.print(BkBasic.java:89)
    at org.takes.http.BkBasic.accept(BkBasic.java:73)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

It looks like afterwords file is actually uploaded (file listed in file list).

When I want to delete that file I'm getting:

```
ava.lang.IllegalArgumentException: header line of HTTP response "Set-Cookie: RsFlash=file deleted;Path=/;Expires=Ĺr, 25 mar 2015 18:46:41 GMT" doesn't match "[a-zA-Z\-]+:\p{Print}+" regular expression, but it should, according to RFC 7230
    at org.takes.rs.RsPrint.print(RsPrint.java:114)
    at org.takes.http.BkBasic.print(BkBasic.java:89)
    at org.takes.http.BkBasic.accept(BkBasic.java:73)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ghost** [comment]
@ggajos file name field is deprecated [#94](https://github.com/teamed/nerodesk/issues/94)

**Comment by yegor256** [comment]
@ggajos this bug is reported in takes: https://github.com/yegor256/takes/issues/76

**Comment by karato** [comment]
I am aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@ggajos thanks for tis bug, I topped your account for 15 mins, transaction `AP-530295969X964935X`

**Comment by karato** [comment]
@krzyk this is your task

**Comment by krzyk** [comment]
@karato give me more time pls

**Comment by karato** [comment]
> @karato give me more time pls

@krzyk of course, thanks for letting me know, take your time

**Comment by krzyk** [comment]
@ggajos PR #137

**Comment by krzyk** [comment]
@ggajos changes have been merged to master, please close this issue

**Comment by ggajos** [comment]
@krzyk thank you

**Comment by karato** [comment]
@krzyk I added **38 mins** to your account, many thanks for working with the project! The completion time here was 54710640.... the bonus for fast delivery (age=2931)... +38 added to your rating, at the moment it is: [+5724](http://www.netbout.com/b/35035?open=rating)
