### ISSUE TITLE
Read and Delete don't work for some filenames

### ISSUE THREAD

**Issue by alevohin** [Nerodesk/nerodesk#160]
`Read` and `Delete` don't work for some filenames.
Steps to reproduce:
- Start application locally by `com.nerodesk.Launch --port=8080`
- Go to the page http://localhost:8080/
- Load file with name `[]().txt`
- Click `Delete` or `Read`

See exception like

```

java.lang.IllegalArgumentException: Malformed escape pair at index 38: http://localhost:8080/doc/delete?file=%5
    at java.net.URI.create(URI.java:859)
    at org.takes.misc.Href.<init>(Href.java:72)
    at org.takes.rq.RqHref.href(RqHref.java:63)
    at org.takes.facets.fork.FkParams.route(FkParams.java:140)
    at org.takes.facets.fork.TsFork.route(TsFork.java:98)
    at org.takes.facets.auth.TsAuth$1.act(TsAuth.java:115)
    at org.takes.facets.fallback.TkFallback.act(TkFallback.java:78)
    at org.takes.http.BkBasic.print(BkBasic.java:89)
    at org.takes.http.BkBasic.accept(BkBasic.java:73)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Malformed escape pair at index 38: http://localhost:8080/doc/delete?file=%5
    at java.net.URI$Parser.fail(URI.java:2829)
    at java.net.URI$Parser.scanEscape(URI.java:2959)
    at java.net.URI$Parser.scan(URI.java:2982)
    at java.net.URI$Parser.checkChars(URI.java:3000)
    at java.net.URI$Parser.parseHierarchical(URI.java:3092)
    at java.net.URI$Parser.parse(URI.java:3034)
    at java.net.URI.<init>(URI.java:595)
    at java.net.URI.create(URI.java:857)
    ... 13 more
```

**Comment by ghost** [comment]
@alevohin interesting, thanks. also see [#94](https://github.com/teamed/nerodesk/issues/94)

**Comment by yegor256** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@yegor256 sure, thanks, I added bug tag to it

**Comment by karato** [comment]
@krzyk do this task

**Comment by karato** [comment]
@alevohin thanks for the ticket, your account was topped for 15 mins, payment 54550284

**Comment by krzyk** [comment]
@alevohin I've created a bug for that in takes (yegor256/takes#126)

**Comment by krzyk** [comment]
@alevohin created PR #187

**Comment by krzyk** [comment]
@alevohin I've added a test case for this (and a todo to upgrade takes when it is fixed there), please close this issue

**Comment by alevohin** [comment]
@krzyk Thank you!

**Comment by karato** [comment]
there is a puzzle in this code `160-88061572`, we'll resolve it later

**Comment by karato** [comment]
@krzyk Much obliged! I have added **38 mins** to your account in payment "55000182", 160 hours and 3 mins spent

there is a bonus for fast delivery (age=2922)

+38 added to your rating, current score is: [+5844](http://www.netbout.com/b/35035?open=rating)

**Comment by karato** [comment]
@alevohin the last puzzle `160-88061572`/#215 originated from here solved
