### ISSUE TITLE
Build in JDK 1.8 fails in cobertura

### ISSUE THREAD

**Issue by krzyk** [Nerodesk/nerodesk#166]
When I build project with JDK 1.8 I get following errors:

```
java.lang.VerifyError: Expecting a stackmap frame at branch target 41
Exception Details:
  Location:
    com/nerodesk/om/aws/AwsDoc.equals(Ljava/lang/Object;)Z @24: if_acmpne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 033d 11ff ff3e 1217 1100 39b8 001d 2b2a
    0x0000010: 1100 393d 1100 003e a600 1112 171c 1d04
    0x0000020: b800 7a11 ffff 3e04 ac1d 9b00 0f12 171c
    0x0000030: 1d03 b800 7a11 ffff 3e2b c100 0211 0039
    0x0000040: 3d11 0001 3e9a 0011 1217 1c1d 04b8 007a
    0x0000050: 11ff ff3e 03ac 1d9b 000f 1217 1c1d 03b8
    0x0000060: 007a 11ff ff3e 2bc0 0002 3a04 2ab4 0022
    0x0000070: 3a05 1904 b400 223a 0619 0511 0039 3d11
    0x0000080: 0002 3ec7 002b 1217 1c1d 04b8 007a 11ff
    0x0000090: ff3e 1906 1100 393d 1100 033e c600 5012
    0x00000a0: 171c 1d04 b800 7a11 ffff 3ea7 0025 1d9b
    0x00000b0: 000f 1217 1c1d 03b8 007a 11ff ff3e 1905
    0x00000c0: 1906 b600 ab11 0039 3d11 0004 3e9a 001f
    0x00000d0: 1c11 0039 a000 161d 1100 04a0 000f 1217
    0x00000e0: 1c1d 04b8 007a 11ff ff3e 03ac 1d9b 000f
    0x00000f0: 1217 1c1d 03b8 007a 11ff ff3e 2ab4 0024
    0x0000100: 3a07 1904 b400 243a 0819 0711 0039 3d11
    0x0000110: 0005 3ec7 002b 1217 1c1d 04b8 007a 11ff
    0x0000120: ff3e 1908 1100 393d 1100 063e c600 5012
    0x0000130: 171c 1d04 b800 7a11 ffff 3ea7 0025 1d9b
    0x0000140: 000f 1217 1c1d 03b8 007a 11ff ff3e 1907
    0x0000150: 1908 b600 ab11 0039 3d11 0007 3e9a 001f
    0x0000160: 1c11 0039 a000 161d 1100 07a0 000f 1217
    0x0000170: 1c1d 04b8 007a 11ff ff3e 03ac 1d9b 000f
    0x0000180: 1217 1c1d 03b8 007a 11ff ff3e 2ab4 0026
    0x0000190: 3a09 1904 b400 263a 0a19 0911 0039 3d11
    0x00001a0: 0008 3ec7 002b 1217 1c1d 04b8 007a 11ff
    0x00001b0: ff3e 190a 1100 393d 1100 093e c600 5012
    0x00001c0: 171c 1d04 b800 7a11 ffff 3ea7 0025 1d9b
    0x00001d0: 000f 1217 1c1d 03b8 007a 11ff ff3e 1909
    0x00001e0: 190a b600 ab11 0039 3d11 000a 3e9a 001f
    0x00001f0: 1c11 0039 a000 161d 1100 0aa0 000f 1217
    0x0000200: 1c1d 04b8 007a 11ff ff3e 03ac 1d9b 000f
    0x0000210: 1217 1c1d 03b8 007a 11ff ff3e 04ac     
  Stackmap Table:
    same_frame(@57)
    same_frame(@102)
    append_frame(@190,Object[#2],Object[#65],Object[#65])
    same_frame(@234)
    same_frame(@252)
    append_frame(@334,Object[#129],Object[#129])
    same_frame(@378)
    same_frame(@396)
    append_frame(@478,Object[#129],Object[#129])
    same_frame(@522)
    same_frame(@540)

    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
    at java.lang.Class.getDeclaredFields(Class.java:1916)
    at nl.jqno.equalsverifier.util.FieldIterable.addFieldsFor(FieldIterable.java:95)
    at nl.jqno.equalsverifier.util.FieldIterable.createFieldList(FieldIterable.java:81)
    at nl.jqno.equalsverifier.util.FieldIterable.iterator(FieldIterable.java:75)
    at nl.jqno.equalsverifier.StaticFieldValueStash.restoreAll(StaticFieldValueStash.java:47)
    at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:367)
    at com.nerodesk.om.aws.AwsDocTest.conformsToEqualsHashCodeContract(AwsDocTest.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

and as a result cobertura check fails with:

```
Cobertura: Loaded information on 38 classes.

[ERROR] Project failed check. Total branch coverage rate of 0.0% is below 50.0%
Project failed check. Total line coverage rate of 14.9% is below 70.0%
```

Project should build with both JDK 1.7 and JDK 1.8 without errors.

Build command: `mvn clean install  -Pqulice,cobertura`.

My environment:

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: /opt/apache-maven-3.2.3
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_40/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.3", arch: "amd64", family: "unix"
```

**Comment by k0r** [comment]
@krzyk thanks.  also see [#18](https://github.com/teamed/nerodesk/issues/18) and [#46](https://github.com/teamed/nerodesk/issues/46)

**Comment by karato** [comment]
@yegor256 please do something about this issue
