### ISSUE TITLE
MkDocTest fails

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#179]
```
guessesContentType(com.nerodesk.om.mock.MkDocTest)  Time elapsed: 0.019 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: "text/plain"
     but: was null
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
    at com.nerodesk.om.mock.MkDocTest.guessesContentType(MkDocTest.java:155)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

This is what I'm doing:

```
mvn clean install -Pqulice,cobertura
```

**Comment by karato** [comment]
@yegor256 got it, tag `bug` is here

**Comment by karato** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-709d8261

**Comment by ghost** [comment]
similar to [#166](https://github.com/teamed/nerodesk/issues/166)

**Comment by caarlos0** [comment]
+1

**Comment by karato** [comment]
@ggajos this is your task

**Comment by ggajos** [comment]
PR #203

**Comment by ghost** [comment]
@ggajos thanks.

**Comment by ggajos** [comment]
@yegor256 your workaround skips assertion and test is no longer complaining; it looks like it's platform dependent, is there something more here?

**Comment by yegor256** [comment]
@ggajos I don't know what is it. not an expert in this problem. the problem was that `Files.probeContentType(this.file().toPath())` returns `null` when type can't be detected (yeah, NULL is an evil, they are not aware of that). so, the only possible solution is to check for `null`:
https://github.com/teamed/nerodesk/blob/master/src/main/java/com/nerodesk/om/mock/MkDoc.java#L89-L92

**Comment by ggajos** [comment]
@yegor256 ok, thanks

**Comment by ggajos** [comment]
@karato we might need more time here

**Comment by ggajos** [comment]
This value is handled by each system natively.

> Windows ignores MIME types, relying only on file extensions. For example, you might have a text file named Example.txt. Windows knows it’s a text file because of the .txt file extension. 
> 
> When you open a file on Linux or Mac OS X, the operating system doesn’t just rely on the file extension. (...) Rather than relying on the file extension at the end of a file’s name, information about the file’s content — the file’s MIME type — is embedded into the beginning of the file itself.

more: http://www.howtogeek.com/192628/mime-types-explained-why-linux-and-mac-os-x-dont-need-file-extensions/

We shouldn't test JVM behaviour.

@yegor256 I think that your fix is solving test issue and we don't need to dig further.

Shall we close then?

**Comment by karato** [comment]
> @karato we might need more time here

@ggajos right, take your time and thanks for informing

**Comment by yegor256** [comment]
@ggajos I agree

**Comment by caarlos0** [comment]
Agree.

**Comment by karato** [comment]
@ggajos Thanks so much! Your account was topped up for **38 mins** (transaction ID is `AP-3NY23448E3241954S`, the task took 166 hours and 31 mins); age=2920, that's why a bonus here for fast delivery; +38 added to your rating, current score is: [+3547](http://www.netbout.com/b/35094?open=rating)
