### ISSUE TITLE
AwsDocsTest fails under windows

### ISSUE THREAD

**Issue by asaen** [Nerodesk/nerodesk#236]
Running locally `mvn -Dtest=AwsDocsTest test` under windows 7 fails with the message:

```
Running com.nerodesk.om.aws.AwsDocsTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.291 sec <<< FAILURE! - in com.nerodesk.om.aws.AwsDocsTest
listsDocs(com.nerodesk.om.aws.AwsDocsTest)  Time elapsed: 0.511 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: <[lists-exists, sub/file]>
     but: was <[lists-exists, sub\file]>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.nerodesk.om.aws.AwsDocsTest.listsDocs(AwsDocsTest.java:143)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by carlosmiranda** [comment]
@darkled Already raised in #199.

**Comment by asaen** [comment]
@carlosmiranda yes, you're right, closing this one..
