### ISSUE TITLE
TkAppTest fails under windows

### ISSUE THREAD

**Issue by asaen** [Nerodesk/nerodesk#237]
Running locally `mvn -Dtest=TkAppTest test` under windows 7 fails with the message:

```
Tests run: 10, Failures: 0, Errors: 2, Skipped: 1, Time elapsed: 20.665 sec <<< FAILURE! - in com.nerodesk.takes.TkAppTest
launchesWebServerInNonLatinLocale(com.nerodesk.takes.TkAppTest)  Time elapsed: 1.945 sec  <<< ERROR!
java.lang.IllegalStateException: broken Unicode text at line #60 in '<!DOCTYPE html\n  SYSTEM "about:legacy-compat">\n<ht..2435..  </nav>\n
     </aside>\n   </body>\n</html>' (2535 bytes)
        at com.jcabi.http.request.DefaultResponse.body(DefaultResponse.java:147)
        at com.jcabi.http.response.AbstractResponse.body(AbstractResponse.java:90)
        at com.jcabi.http.response.XmlResponse.body(XmlResponse.java:82)
        at com.jcabi.http.response.XmlResponse.assertXPath(XmlResponse.java:142)
        at com.nerodesk.takes.TkAppTest$2.exec(TkAppTest.java:139)
        at org.takes.http.FtRemote.exec(FtRemote.java:118)
        at com.nerodesk.takes.TkAppTest.launchesWebServerInNonLatinLocale(TkAppTest.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

launchesOnRandomPort(com.nerodesk.takes.TkAppTest)  Time elapsed: 1.945 sec  <<< ERROR!
java.lang.IllegalStateException: broken Unicode text at line #60 in '<!DOCTYPE html\n  SYSTEM "about:legacy-compat">\n<ht..2435..  </nav>\n
     </aside>\n   </body>\n</html>' (2535 bytes)
        at com.jcabi.http.request.DefaultResponse.body(DefaultResponse.java:147)
        at com.jcabi.http.response.AbstractResponse.body(AbstractResponse.java:90)
        at com.jcabi.http.response.XmlResponse.body(XmlResponse.java:82)
        at com.jcabi.http.response.XmlResponse.assertXPath(XmlResponse.java:142)
        at com.nerodesk.takes.TkAppTest$1.exec(TkAppTest.java:106)
        at org.takes.http.FtRemote.exec(FtRemote.java:118)
        at com.nerodesk.takes.TkAppTest.launchesOnRandomPort(TkAppTest.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by carlosmiranda** [comment]
@darkled Confirming that I get the same error.

**Comment by yegor256** [comment]
@darkled @carlosmiranda see 13e4720

**Comment by asaen** [comment]
@yegor256 thank you, it works.
