### ISSUE TITLE
/doc/write causes IOException on server

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#242]
This is what is happening when I upload a big file (over 50Mb), although everything works fine with a small (5Kb) file:

```
2015-04-24T17:32:03.201630+00:00 heroku[router]: sock=backend at=error code=H18 desc="Request Interrupted" method=POST path="/doc/write" host=beta.nerodesk.com request_id=d5e8fcb1-ad25-48ed-ada5-442a657fe02b fwd="64.245.0.218" dyno=web.1 connect=5ms service=419ms status=503 bytes=482
2015-04-24T17:32:03.175656+00:00 app[web.1]: 29f5f46 com.nerodesk.om.aws.AwsDoc: com.jcabi.s3.retry.ReOcket@ef2bdc1a written
2015-04-24T17:33:57.726948+00:00 app[web.1]: java.io.IOException: a valid request must contain at least one line in the head
2015-04-24T17:33:57.726953+00:00 app[web.1]:    at org.takes.rq.RqCookies$Base.map(RqCookies.java:121)
2015-04-24T17:33:57.726956+00:00 app[web.1]:    at org.takes.facets.flash.TkFlash.act(TkFlash.java:95)
2015-04-24T17:33:57.726958+00:00 app[web.1]:    at org.takes.tk.TkVerbose$1.act(TkVerbose.java:57)
2015-04-24T17:33:57.726943+00:00 app[web.1]: 29f5f46 com.nerodesk.takes.FbError$1: Exception thrown
2015-04-24T17:33:57.726955+00:00 app[web.1]:    at org.takes.rq.RqCookies$Base.cookie(RqCookies.java:82)
2015-04-24T17:33:57.726952+00:00 app[web.1]:    at org.takes.rq.RqHeaders.header(RqHeaders.java:67)
2015-04-24T17:33:57.726963+00:00 app[web.1]:    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
2015-04-24T17:33:57.726965+00:00 app[web.1]:    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
2015-04-24T17:33:57.726966+00:00 app[web.1]:    at org.takes.tk.TkWrap.act(TkWrap.java:59)
2015-04-24T17:33:57.726968+00:00 app[web.1]:    at org.takes.tk.TkWrap.act(TkWrap.java:59)
2015-04-24T17:33:57.726969+00:00 app[web.1]:    at org.takes.http.BkBasic.print(BkBasic.java:94)
2015-04-24T17:33:57.726970+00:00 app[web.1]:    at org.takes.http.BkBasic.accept(BkBasic.java:75)
2015-04-24T17:33:57.726972+00:00 app[web.1]:    at org.takes.http.BkSafe.accept(BkSafe.java:58)
2015-04-24T17:33:57.726974+00:00 app[web.1]:    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
2015-04-24T17:33:57.726975+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2015-04-24T17:33:57.726977+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2015-04-24T17:33:57.726978+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:745)
2015-04-24T17:33:57.726980+00:00 app[web.1]:
2015-04-24T17:33:57.726950+00:00 app[web.1]:    at org.takes.rq.RqHeaders.map(RqHeaders.java:110)
2015-04-24T17:33:57.726959+00:00 app[web.1]:    at org.takes.tk.TkWrap.act(TkWrap.java:59)
2015-04-24T17:33:57.726961+00:00 app[web.1]:    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
```

**Comment by yegor256** [comment]
@karato pls assign @krzyk to this issue

**Comment by karato** [comment]
@yegor256 we will find someone to do this task, soon

**Comment by karato** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by yegor256** [comment]
@karato pls set milestone to 0.4

**Comment by karato** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-61a78fe0

**Comment by karato** [comment]
> @karato pls assign @krzyk to this issue

@yegor256 yep, done. @krzyk it is your task now

**Comment by karato** [comment]
> @karato pls set milestone to 0.4

@yegor256 sure, milestone set to 0.4

**Comment by krzyk** [comment]
@yegor256 I can't recreate this problem. I've created S3 bucket and uploaded there a small file, and then a large >50MB one without any problems. But I've done it on localhost, maybe the problem is that a large file takes to much time to upload to heroku and the server closes the connection there?
Or maybe even further, slow file upload to heroku results in slow upload to S3 and eventually amazon closes the connection.

**Comment by krzyk** [comment]
@yegor256 I just tried to upload 200MB file and it uploaded just fine.

**Comment by krzyk** [comment]
@yegor256 Although I see the exception thrown (only in the logs, not in the UI), that is almost identical to the one you posted, but the file uploaded fine and is accessible.
When you do the upload, does it fail completly with no access to the file?

**Comment by yegor256** [comment]
@krzyk on production I can also upload a file without problems, but I see this exception in the logs. I suspect that something is happening behind the scene...

**Comment by krzyk** [comment]
@karato give me more time here

**Comment by karato** [comment]
> @karato give me more time here

@krzyk sure, take your time

**Comment by krzyk** [comment]
Sorry, I tried several times to find the root cause but I failed.

**Comment by krzyk** [comment]
@k0r please assign someone else

**Comment by k0r** [comment]
@krzyk [yegor256/takes#248](https://github.com/yegor256/takes/issues/248) could be related to this problem

**Comment by krzyk** [comment]
@k0r I don't think so, I was able to recreate this problem even with small files. To recreate it (but only sometimes!) one can:
1. start the application with mocks
2. load the main page
3. upload any file (even 1 byte)
4. refresh the page 

At 4 usually the stacktrace appears in the logs.
Also one has to readd `Logger.info(this, "Exception thrown\n%s", exc);` to `FbError` class, it is right now ignored in master.

**Comment by k0r** [comment]
@krzyk check [this](https://github.com/dmzaytsev/takes/commit/63e952e8dc23ebccdae3922902dc61ea38fe0d46) out. `IOException` is modified.

**Comment by krzyk** [comment]
@karato please assign someone else

**Comment by karato** [comment]
> @karato please assign someone else

@krzyk -30 points to your rating

**Comment by karato** [comment]
> @karato please assign someone else

@krzyk I will assign somebody else to this issue
