### ISSUE TITLE
Unable to execute HTTP request: Stream Closed

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#253]
tried to upload a file and got this:

```

oops, something went wrong!
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Stream Closed
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:471)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3699)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1434)
    at com.jcabi.s3.AwsOcket.write_aroundBody10(AwsOcket.java:188)
    at com.jcabi.s3.AwsOcket$AjcClosure11.run(AwsOcket.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.jcabi.s3.AwsOcket.write(AwsOcket.java:184)
    at com.jcabi.s3.retry.ReOcket.write_aroundBody16(ReOcket.java:100)
    at com.jcabi.s3.retry.ReOcket$AjcClosure17.run(ReOcket.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:81)
    at com.jcabi.s3.retry.ReOcket.write(ReOcket.java:100)
    at com.nerodesk.om.aws.AwsDoc.write(AwsDoc.java:145)
    at com.nerodesk.om.SmallDoc.write(SmallDoc.java:116)
    at com.nerodesk.takes.doc.TkWrite.act(TkWrite.java:86)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:125)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:159)
    at org.takes.facets.fork.TkFork.act(TkFork.java:99)
    at com.nerodesk.takes.doc.TkDoc.act(TkDoc.java:66)
    at org.takes.facets.auth.TkSecure.act(TkSecure.java:84)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:125)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:159)
    at org.takes.facets.fork.TkFork.act(TkFork.java:99)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:113)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
    at org.takes.tk.TkVerbose$1.act(TkVerbose.java:57)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.http.BkBasic.print(BkBasic.java:94)
    at org.takes.http.BkBasic.accept(BkBasic.java:75)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Stream Closed
    at java.io.FileInputStream.readBytes(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:272)
    at com.nerodesk.om.ThresholdInputStream.read(ThresholdInputStream.java:140)
    at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:98)
    at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
    at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:108)
    at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
    at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.read(MD5DigestCalculatingInputStream.java:98)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at com.amazonaws.internal.SdkBufferedInputStream.read(SdkBufferedInputStream.java:76)
    at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
    at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:151)
    at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
    at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:138)
    at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:153)
    at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntit
```

I think this is the cause of the issue (from heroku logs): 

```
cf3e136 com.jcabi.s3.AwsOcket: #write(java.io.FileInputStream@6a07e6da, com.amazonaws.services.s3.model.ObjectMetadata@2cc52898): 
thrown com.amazonaws.AmazonClientException(Data read has a different 
length than the expected: dataLength=2747; expectedLength=242583; 
includeSkipped=false; in.getClass()=class 
org.apache.commons.io.input.CountingInputStream; markedSupported=false; 
marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0) 
out of com.amazonaws.util.LengthCheckInputStream#checkLength[150] in 299ms
```

Then I see this:

```
cf3e136 com.jcabi.s3.retry.ReOcket: #write(): attempt #3/3 failed 
with com.amazonaws.AmazonClientException in 2s (5s in total): 
Unable to execute HTTP request: Stream Closed; Stream Closed
```

So, this `stream closed` is not the root cause of the problem. It happens only because `ReOcket` is retrying to upload and the source stream is already closed. It's logical.

**Comment by yegor256** [comment]
@karato pls assign @krzyk to this

**Comment by yegor256** [comment]
no matter what is the size of the file, I see the same situation

**Comment by krzyk** [comment]
@yegor256 looks like we can't depend on content-length from http request as it is impossible to count number of bytes of the original file from it (multipart encoding + gzip). So for this to work we should implement multipart sending to S3 (jcabi/jcabi-s3#29), and the current content-length functionality should be removed.

Besides that I think it would be great to have integration tests (using failsafe) that would work on real AWS keys so we could avoid such bugs in the future.

Should I remove the content-length here and work on the integration test also?

**Comment by karato** [comment]
@yegor256 I am aware of the task, give me some time to find a developer...

**Comment by yegor256** [comment]
@krzyk I'm not sure you're right about "it is impossible to count number of bytes of the original file from it". can you explain more, with an example?

**Comment by krzyk** [comment]
@yegor256 The only way that we could get the file size is by browsers communicating it to us, the only way it is possible in HTTP is by using `Content-length` header, but this header contains all the data that is sent to the server, including multipart encoding headers and footers (which can have different lengths).
But the whole content can be also compressed, and Content-lenght in such case would show the compressed length of the uploaded file. So we will know the total lenght only after decompressing the stream and counting the bytes.

**Comment by yegor256** [comment]
@krzyk not exactly. when we receive a request, `RqMultipart` is unzipping it and saving to a temporary file. That's the first step. Then, it parses the file and returns an individual "request" per each part. Why can't we know the size of each part?

**Comment by karato** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-52d38df4`

**Comment by karato** [comment]
> @karato pls assign @krzyk to this

@yegor256 OK @krzyk please go ahead, this task is yours

**Comment by krzyk** [comment]
@yegor256 OK, I didn't check the source for RqMultipart, in such case it would be enough to extend `RqMutlipart` to return the size of the file, not only it's name and request body.
I've created issue for this yegor256/takes#226

**Comment by krzyk** [comment]
@yegor256 PR #259

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.17`

**Comment by yegor256** [comment]
@krzyk this problem is gone

**Comment by karato** [comment]
@krzyk Thanks a lot, I just topped your account for **30 mins**, transaction ID `56465485`, total time was 52 hours and 35 mins

added +30 to your rating, now it is equal to [+4842](http://www.netbout.com/b/35035?open=rating)
