### ISSUE TITLE
file name causes file upload error

### ISSUE THREAD

**Issue by pinaf** [Nerodesk/nerodesk#275]
I suspect this is because of the name of the file I tried to upload. It has uncommon characters: `Æsop_s_Fables_as_Romanized_by_Phædrus.pdf`

If so, there encoding of the file name should be used if we expect the system to handle UNICODE file names.

```
oops, something went wrong!
org.takes.HttpException: POST http://localhost:8080/doc/write
    at org.takes.tk.TkVerbose$1.act(TkVerbose.java:59)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.http.FtCLI$1.act(FtCLI.java:84)
    at org.takes.http.BkBasic.print(BkBasic.java:93)
    at org.takes.http.BkBasic.accept(BkBasic.java:74)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.takes.HttpException: illegal character 0xC3 in HTTP header line #2: "Content-Disposition: form-data; name="file"; filename=""
    at org.takes.rq.RqLive.parse(RqLive.java:93)
    at org.takes.rq.RqLive.<init>(RqLive.java:55)
    at org.takes.rq.RqMultipart$Base.make(RqMultipart.java:229)
    at org.takes.rq.RqMultipart$Base.<init>(RqMultipart.java:159)
    at com.nerodesk.takes.doc.TkWrite.act(TkWrite.java:75)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:146)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:180)
    at org.takes.facets.fork.TkFork.act(TkFork.java:99)
    at com.nerodesk.takes.doc.TkDoc.act(TkDoc.java:66)
    at org.takes.facets.auth.TkSecure.act(TkSecure.java:84)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:146)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:180)
    at org.takes.facets.fork.TkFork.act(TkFork.java:99)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:113)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
    at org.takes.tk.TkVerbose$1.act(TkVerbose.java:57)
    ... 15 more
```

**Comment by k0r** [comment]
@pinaf regex omits uncommon characters. the system should instruct the user to rename the file before retrying the file upload.

**Comment by k0r** [comment]
@pinaf thanks.

**Comment by pinaf** [comment]
@k0r np

**Comment by karato** [comment]
@yegor256 please do something about this issue
