### ISSUE TITLE
server requires handling multiple requests

### ISSUE THREAD

**Issue by k0r** [Nerodesk/nerodesk#312]
unable to access www.nerodesk.com. here are the stack traces:

```
oops, something went wrong!
com.amazonaws.AmazonClientException: Unable to execute HTTP request: data.nerodesk.teamed.io.s3.amazonaws.com
    [...]
Caused by: java.net.UnknownHostException: data.nerodesk.teamed.io.s3.amazonaws.com
```

and from [this](https://github.com/Nerodesk/nerodesk/issues/312#issuecomment-108654045):

`Exception in thread "main" java.net.SocketException: Too many open files`

if the server has too many requests for file `read` then it causes the referenced errors.

**Comment by k0r** [comment]
@yegor256 seems to have been fixed. perhaps `aws` was down. will keep this ticket open for a few hours to verify.

**Comment by yegor256** [comment]
@k0r they are not saying about it: http://status.aws.amazon.com/

**Comment by yegor256** [comment]
@k0r here is what I see in logs:

```
2015-06-03T17:40:53.538426+00:00 app[web.1]: 96d52bd com.jcabi.s3.AwsBucket: #list('urn:facebook:832319836861231/'): thrown com.amazonaws.AmazonClientException(Unable to execute HTTP request: data.nerodesk.teamed.io.s3.amazonaws.com) out of com.amazonaws.http.AmazonHttpClient#executeHelper[471] in 2s
2015-06-03T17:40:53.539173+00:00 app[web.1]: 96d52bd com.jcabi.s3.retry.ReBucket: #list(): attempt #1/3 failed with com.amazonaws.AmazonClientException in 2s (2s in total): Unable to execute HTTP request: data.nerodesk.teamed.io.s3.amazonaws.com; data.nerodesk.teamed.io.s3.amazonaws.com
2015-06-03T17:40:55.449047+00:00 app[web.1]: 96d52bd com.jcabi.s3.AwsBucket: #list('urn:facebook:832319836861231/'): thrown com.amazonaws.AmazonClientException(Unable to execute HTTP request: data.nerodesk.teamed.io.s3.amazonaws.com) out of com.amazonaws.http.AmazonHttpClient#executeHelper[471] in 2s
2015-06-03T17:40:55.449639+00:00 app[web.1]: 96d52bd com.jcabi.s3.retry.ReBucket: #list(): attempt #2/3 failed with com.amazonaws.AmazonClientException in 2s (4s in total): Unable to execute HTTP request: data.nerodesk.teamed.io.s3.amazonaws.com; data.nerodesk.teamed.io.s3.amazonaws.com
2015-06-03T17:40:57.455593+00:00 app[web.1]: 96d52bd com.jcabi.s3.AwsBucket: #list('urn:facebook:832319836861231/'): thrown com.amazonaws.AmazonClientException(Unable to execute HTTP request: data.nerodesk.teamed.io.s3.amazonaws.com) out of com.amazonaws.http.AmazonHttpClient#executeHelper[471] in 2s
2015-06-03T17:40:57.456395+00:00 app[web.1]: 96d52bd com.jcabi.s3.retry.ReBucket: #list(): attempt #3/3 failed with com.amazonaws.AmazonClientException in 2s (6s in total): Unable to execute HTTP request: data.nerodesk.teamed.io.s3.amazonaws.com; data.nerodesk.teamed.io.s3.amazonaws.com
2015-06-03T17:41:27.234444+00:00 app[web.1]: Exception in thread "main" java.net.SocketException: Too many open files
2015-06-03T17:41:27.235118+00:00 app[web.1]:    at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
2015-06-03T17:41:27.235253+00:00 app[web.1]:    at java.net.ServerSocket.implAccept(ServerSocket.java:530)
2015-06-03T17:41:27.235477+00:00 app[web.1]:    at org.takes.http.FtBasic.loop(FtBasic.java:94)
2015-06-03T17:41:27.235376+00:00 app[web.1]:    at java.net.ServerSocket.accept(ServerSocket.java:498)
2015-06-03T17:41:27.235837+00:00 app[web.1]:    at org.takes.http.FtBasic.start(FtBasic.java:80)
2015-06-03T17:41:27.234901+00:00 app[web.1]:    at java.net.PlainSocketImpl.socketAccept(Native Method)
2015-06-03T17:41:27.235978+00:00 app[web.1]:    at org.takes.http.FtCLI.start(FtCLI.java:120)
2015-06-03T17:41:27.236083+00:00 app[web.1]:    at com.nerodesk.Launch.exec(Launch.java:80)
2015-06-03T17:41:27.236202+00:00 app[web.1]:    at com.nerodesk.Launch.main(Launch.java:72)
```

**Comment by k0r** [comment]
@yegor256 `Exception in thread "main" java.net.SocketException: Too many open files`

**Comment by k0r** [comment]
@yegor256 I think I know what caused this. I'll update and rename the ticket once confirmed.

**Comment by k0r** [comment]
@yegor256 updated.

**Comment by yegor256** [comment]
@k0r let's monitor this... I suspect it was a one-time issue in Heroku

**Comment by k0r** [comment]
@yegor256 thanks.
