### ISSUE TITLE
LaunchTest.returnsFileContent randomly fails

### ISSUE THREAD

**Issue by alevohin** [Nerodesk/nerodesk#78]
LaunchTest.returnsFileContent randomly fails. Log below:

```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.997 sec <<< FAILURE! - in com.nerodesk.LaunchTest
returnsFileContent(com.nerodesk.LaunchTest)  Time elapsed: 3.882 sec  <<< ERROR!
com.jayway.awaitility.core.ConditionTimeoutException: com.nerodesk.LaunchTest.returnsFileContent Callable expected "some text content" but was <null> within 2 seconds.
    at com.jayway.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:96)
    at com.jayway.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:87)
    at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:590)
    at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:408)
    at com.nerodesk.LaunchTest.returnsFileContent(LaunchTest.java:134)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Results :
Tests in error: 
  LaunchTest.returnsFileContent:134 » ConditionTimeout com.nerodesk.LaunchTest.r...
```

Please see https://travis-ci.org/teamed/nerodesk/builds/54266652 for full log.

**Comment by yegor256** [comment]
@alevohin please, try again now. It was an issue in takes, I believe. It's fixed in the latest version

**Comment by alevohin** [comment]
@yegor256 I cannot reproduce it. I checked last PR's and master's states - this error is not reproduced also.
