### ISSUE TITLE
RqMultipart can only parse multipart/form-data...

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#82]
```
java.io.IOException: RqMultipart can only parse multipart/form-data, while Content-Type specifies a different type: application/x-www-form-urlencoded
    at org.takes.rq.RqMultipart.<init>(RqMultipart.java:87)
    at com.nerodesk.TkWrite.act(TkWrite.java:73)
    at org.takes.facets.auth.TsAuth$1.act(TsAuth.java:115)
    at org.takes.http.BkBasic.print(BkBasic.java:89)
    at org.takes.http.BkBasic.accept(BkBasic.java:73)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkParalle
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.3`

**Comment by karato** [comment]
@yegor256 your task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-ece6c71e

**Comment by yegor256** [comment]
fixed

**Comment by karato** [comment]
@yegor256 paid, thanks, added **30 mins** to your account, payment `000-2825c5b8`... +30 added to your rating, at the moment it is: [+8403](http://www.netbout.com/b/35008?open=rating)
