### ISSUE TITLE
file upload doesn't work

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#83]
```
java.lang.IndexOutOfBoundsException: Index: 0
    at java.util.Collections$EmptyList.get(Collections.java:3212)
    at java.util.Collections$UnmodifiableList.get(Collections.java:1211)
    at com.nerodesk.TkWrite.act(TkWrite.java:75)
    at org.takes.facets.auth.TsAuth$1.act(TsAuth.java:115)
    at org.takes.http.BkBasic.print(BkBasic.java:89)
    at org.takes.http.BkBasic.accept(BkBasic.java:73)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@rultor release tag is `0.1.4`

**Comment by karato** [comment]
@yegor256 your task, 30 mins is budget

**Comment by karato** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-6bceaab1`

**Comment by karato** [comment]
@yegor256 **30 mins** was added to your account, many thanks for your contribution!. +30 to your rating, your total score is [+8433](http://www.netbout.com/b/35008?open=rating)
