### ISSUE TITLE
AWS upload/download doesn't work

### ISSUE THREAD

**Issue by yegor256** [Nerodesk/nerodesk#85]
```
com.jcabi.s3.OcketNotFoundException: ocket '/urn:facebook:10206246356747784/urn:facebook:10206246356747784face.jpg' not found in 'data.nerodesk.teamed.io'
    at com.jcabi.s3.AwsOcket.read_aroundBody8(AwsOcket.java:168)
    at com.jcabi.s3.AwsOcket$AjcClosure9.run(AwsOcket.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.jcabi.s3.AwsOcket.read(AwsOcket.java:150)
    at com.jcabi.s3.retry.ReOcket.read_aroundBody12(ReOcket.java:93)
    at com.jcabi.s3.retry.ReOcket$AjcClosure13.run(ReOcket.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:81)
    at com.jcabi.s3.retry.ReOcket.read(ReOcket.java:93)
    at com.nerodesk.om.aws.AwsDoc.read(AwsDoc.java:95)
    at com.nerodesk.TkRead.act(TkRead.java:65)
    at org.takes.facets.auth.TsAuth$1.act(TsAuth.java:115)
    at org.takes.http.BkBasic.print(BkBasic.java:89)
    at org.takes.http.BkBasic.accept(BkBasic.java:73)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: E9B938D8839A35A8), S3 Extended Request ID: aC1Gv21UIoHFlT7ho7ZeqZtJ699b5Cr2o2Mb0URdVbLIf22v65gbwRAwfUsoKpJviTnIOIFJDGw=
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:820)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:439)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:245)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3722)
    at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1137)
    at com.jcabi.s3.AwsOcket.read_aroundBody8(AwsOcket.java:153)
    ... 21 more
```

**Comment by karato** [comment]
@yegor256 got it, tag `bug` is here

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.6`

**Comment by karato** [comment]
@krzyk this is your task

**Comment by karato** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-5c8605b2`

**Comment by karato** [comment]
@krzyk I don't see any messages from you above, not sure if there was actual contribution (correct me if I'm wrong)

**Comment by qhysjpw** [comment]
zz

**Comment by qhysjpw** [comment]
I also encountered the same problem！！！！Can anyone tell me how to solve....

**Comment by qhysjpw** [comment]
@yegor256 Man, you begin to solve this problem ?
