### ISSUE TITLE
TkDeleteTest.deletesFiles() test failure (possibly environment specific)

### ISSUE THREAD

**Issue by carlosmiranda** [Nerodesk/nerodesk#95]
When I build with `mvn clean install -Pqulice,cobertura`, I get the following test failure:

```
Running com.nerodesk.TkDeleteTest
[←[0;37mINFO←[m] com.nerodesk.om.mock.MkDoc: C:\Users\U24031\AppData\Local\Temp\1426727590166-0\urn\test\1\hey saved
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec <<< FAILURE! - in com.nerodesk.TkDeleteTest
deletesFile(com.nerodesk.TkDeleteTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: an empty iterable
     but: ["hey"]
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.nerodesk.TkDeleteTest.deletesFile(TkDeleteTest.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Running com.nerodesk.TkReadTest
[←[0;37mINFO←[m] com.nerodesk.om.mock.MkDoc: C:\Users\U24031\AppData\Local\Temp\1426727590142-0\urn\test\1\hey saved
[←[0;37mINFO←[m] com.nerodesk.om.mock.MkDoc: C:\Users\U24031\AppData\Local\Temp\1426727590142-0\urn\test\1\hey loaded
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec - in com.nerodesk.TkReadTest

Results :

Failed tests:
  TkDeleteTest.deletesFile:63
Expected: an empty iterable
     but: ["hey"]

Tests run: 8, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.416 s
[INFO] Finished at: 2015-03-19T09:13:11+08:00
[INFO] Final Memory: 31M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project nerodesk: There are test failures.
```

Judging by the fact that the recent Travis and Rultor builds have passed, I believe this is an environment-specific (Windows?) problem. See output of my `mvn --version` below:

```
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-15T01:37:52+08:00)
Maven home: D:\apache-maven-3.2.1
Java version: 1.7.0_55, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_55\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
```

**Comment by yegor256** [comment]
@karato looks like a Win-related bug to me

**Comment by karato** [comment]
> @karato looks like a Win-related bug to me

@yegor256 OK, I labeled it as `bug`

**Comment by karato** [comment]
@longtimeago do this task

**Comment by karato** [comment]
@carlosmiranda thanks for this report, I added 15 mins to your account, in transaction `53782840`

**Comment by longtimeago** [comment]
@karato please, assign someone else. I have no windows PC available now

**Comment by karato** [comment]
> @karato please, assign someone else. I have no windows PC available now

@longtimeago right, I'll try to find someone else for this task

**Comment by karato** [comment]
@pinaf do this task

**Comment by pinaf** [comment]
@karato please assign someone else. no windows here either.

**Comment by karato** [comment]
> @karato please assign someone else. no windows here either.

@pinaf no problem, I will try to find somebody else

**Comment by karato** [comment]
@alevohin this is your task

**Comment by alevohin** [comment]
@karato I cannot reproduce it, I get 

```
[[0;37mINFO[m] com.nerodesk.om.mock.MkDoc: C:\Users\YURIY~1.ALE\AppData\Local\Temp\1427310973245-0\urn\test\1\hey saved

java.lang.IllegalArgumentException: header line of HTTP response "Set-Cookie: RsFlash=file deleted;Path=/;Expires=Ср, 25 мар 2015 23:16:13 GMT" doesn't match "[a-zA-Z\-]+:\p{Print}+" regular expression, but it should, according to RFC 7230
    at org.takes.rs.RsPrint.print(RsPrint.java:114)
    at org.takes.rs.RsPrint.print(RsPrint.java:77)
    at com.nerodesk.TkDeleteTest.deletesFile(TkDeleteTest.java:60)
```

It looks that we need wait for https://github.com/teamed/nerodesk/issues/137

**Comment by alevohin** [comment]
@karato we need to wait for https://github.com/yegor256/takes/issues/76 and then update `takes` version.

**Comment by alevohin** [comment]
@karato lets wait yegor256/takes#76 and #137 because this problem is not reproducable right now.

**Comment by carlosmiranda** [comment]
@karato we're waiting for #137.

**Comment by karato** [comment]
> @karato we're waiting for #137.

@carlosmiranda ok, let's wait for #137

**Comment by karato** [comment]
FYI, issue #137 is already closed, and we were waiting for it..

**Comment by alevohin** [comment]
@carlosmiranda PR #185 was merged.

`MkDoc.write` didn't close FileInputStream so MkDoc.delete couldn't delete temp file. Method `File.delete` returned false, but it was ignored. Test `TkDeleteTest` failed (problem was reproduced in Windows and OSX, for Windows - constantly). Fixed - properly closing FileInputStream.

Please check and close issue.

**Comment by carlosmiranda** [comment]
@alevohin Very good, thanks! Closing...

**Comment by karato** [comment]
@alevohin **38 mins** was added to your account, many thanks for your contribution! The task took 55000170.... there is a bonus for fast delivery (age=2949)... +38 added to your rating, current score is: [+2168](http://www.netbout.com/b/35105?open=rating)
